name: Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: [self-hosted, Linux, X64, sre/foundation-l1]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Integration
        run: make integration
